version: "3.7"

services:
  app:
    build: .
    depends_on:
      - db
      - webpack
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file:
      - .env
      - .env.development
    environment:
      RAILS_ENV: development
  db:
    image: postgres:12.2
    volumes:
      - db_data:/var/lib/postgresql/data
  webpack:
    build: .
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    entrypoint: ./entrypoints/webpack-entrypoint.sh


volumes:
  gem_cache:
  db_data:
  node_modules:
